server:
  port: 9090

spring:
  thymeleaf:
    cache: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: 123456
    username: root
    druid:
      max-active: 20
      max-wait: 10000
      min-idle: 5
      filters: log4j

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

# token 过期时间 （俩小时）
token:
  expire:
    seconds: 7200
  jwt:
    secret: ($%^FGH3J)_(DFCT12VGYB%&)_^_^_&@#$%^&hjvbsdauij&_(###)