


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/market?serverTimezone+GMT%2B8

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true